### ISSUE TITLE
Check Cargo.lock into version control?

### ISSUE THREAD

**Issue by botandrose** [BartMassey/rocket-pastebin#3]

**Comment by BartMassey** [comment]
I'm not sure what best practice is here. Arguably, it's a bug if Cargo.toml doesn't specify a minimum set of dependency versions; wouldn't it be better to let each installation have their own Cargo.lock? IDK...

**Comment by botandrose** [comment]
I feel pretty confident in saying that Cargo.lock should be checked in,
because this is ultimately an application, not a library, and you want to
make sure everyone is running the same code to prevent "works on my
machine" issues. Additionally, the developers of cargo are the same as the
developers of bundler (Yehuda Katz again), so it seems the same
philosophies apply.

**Comment by BartMassey** [comment]
I don't feel strongly about it, so I'll check it in. I certainly agree that this is what Katz et al intended. I'm not as convinced that it's the right thing :-). The biggest problem with it is that the codebase now requires constant maintenance to compile: the `Cargo.lock` will cease to work over time otherwise as packages become unavailable or uninstallable. I think.

**Comment by botandrose** [comment]
I understand what you're saying, but I'd counter-argue that the codebase already would require maintenance to compile as the years go on. Checking in Cargo.lock is sort of an admission to that reality.
