### ISSUE TITLE
.gitignore target directory?

### ISSUE THREAD

**Issue by botandrose** [BartMassey/rocket-pastebin#4]

**Comment by BartMassey** [comment]
I prefer not to check in gitignore files, in general: they tend to be sort of personal-preference, and the checked-in ones collide with folks' custom ones and make a mess. Not really sure what is best practice here... (I have the target/ directory in my global gitignore, but updates/ is in a local one.)

**Comment by botandrose** [comment]
It's always interesting to collaborate with you on projects, Bart, because I get exposed to viewpoints that I wouldn't have, otherwise, in my ruby echo chamber. I've never heard of anyone avoiding checking in `.gitignore`, for example, and would have never even considered the merits of doing it vs not.

I generally like to `git add -A` and then `git commit`, so I'd prefer build artifacts be gitignored, but its not a big deal.

**Comment by BartMassey** [comment]
Oh, build artifacts need to be gitignored. My recommended strategy is to use your global gitignore file for standard build artifacts: that way there is often no need for per-project ignores. My current one looks like [this](http://pastebin.com/Cpjqa4zQ).

To me the question is whether the gitignore for things that are "special" to the project should be checked in. And like I say, the only reason I don't is that I inevitably have some of my own per-wd crap sitting in there, and every time I `git pull` my `.gitignore` gets clobbered, so I end up using `git update-index --assume-unchanged .gitignore` and then I forget to undo that when I make a change that really *should* be global, plus it's a pain to make that change because I have to move-aside my hacked `.gitignore`...

So...yeah.

**Comment by botandrose** [comment]
Why not just add your per-wd crap to the .gitignore and check it in?

**Comment by BartMassey** [comment]
Because then everyone else gets it whether they want it or not? It shouldn't normally cause them problems, but depending on what it is (`*.py`) it sure could...

**Comment by botandrose** [comment]
I guess I just don't see the problem you're solving. Why would you need .py
in the working dir gitignore? And if you did, why would that bother someone
else? It seems like you're solving a problem that doesn't exist, but the
solution is creating problems for both you and potential collaborators. Why
not just use gitignore like everyone else?

**Comment by BartMassey** [comment]
As you will. Fixed in c12e0a0.

**Comment by botandrose** [comment]
<3
